python3 ppo_continuous_action.py --exp_name ppo_n_1_no_noise --n 1 --env_id Nav2D-v0 --seed 10 --total_timesteps 500_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_1_no_noise --n 1 --env_id Nav2D-v0 --seed 11 --total_timesteps 500_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_1_no_noise --n 1 --env_id Nav2D-v0 --seed 12 --total_timesteps 500_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_1_no_noise --n 1 --env_id Nav2D-v0 --seed 13 --total_timesteps 500_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null

python3 ppo_continuous_action.py --exp_name ppo_n_2_no_noise --n 2 --env_id Nav2D-v0 --seed 10 --total_timesteps 500_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_2_no_noise --n 2 --env_id Nav2D-v0 --seed 11 --total_timesteps 500_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_2_no_noise --n 2 --env_id Nav2D-v0 --seed 12 --total_timesteps 500_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_2_no_noise --n 2 --env_id Nav2D-v0 --seed 13 --total_timesteps 500_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null

python3 ppo_continuous_action.py --exp_name ppo_n_3_no_noise --n 3 --env_id Nav2D-v0 --seed 10 --total_timesteps 800_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_3_no_noise --n 3 --env_id Nav2D-v0 --seed 11 --total_timesteps 800_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_3_no_noise --n 3 --env_id Nav2D-v0 --seed 12 --total_timesteps 800_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_3_no_noise --n 3 --env_id Nav2D-v0 --seed 13 --total_timesteps 800_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null

python3 ppo_continuous_action.py --exp_name ppo_n_5_no_noise --n 5 --env_id Nav2D-v0 --seed 10 --total_timesteps 800_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_5_no_noise --n 5 --env_id Nav2D-v0 --seed 11 --total_timesteps 800_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_5_no_noise --n 5 --env_id Nav2D-v0 --seed 12 --total_timesteps 800_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_5_no_noise --n 5 --env_id Nav2D-v0 --seed 13 --total_timesteps 800_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null

python3 ppo_continuous_action.py --exp_name ppo_n_7_no_noise --n 7 --env_id Nav2D-v0 --seed 10 --total_timesteps 900_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_7_no_noise --n 7 --env_id Nav2D-v0 --seed 11 --total_timesteps 900_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_7_no_noise --n 7 --env_id Nav2D-v0 --seed 12 --total_timesteps 900_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
python3 ppo_continuous_action.py --exp_name ppo_n_7_no_noise --n 7 --env_id Nav2D-v0 --seed 13 --total_timesteps 900_000 --wandb_entity elefort-org --wandb_project_name 2d_navigator --capture_video --track --save_model --num_envs 3 > /dev/null
